spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${CATALOG_SVC_MYSQL_URL} 
    username: ${CATALOG_SVC_MYSQL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${CATALOG_SVC_MYSQL_PASSWORD}