spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
    hibernate:
      ddl-auto: update
  datasource:
    url: ${MYSQL_URL} 
    username: ${MYSQL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}