
server:
  port: 9000
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
    hibernate:
      ddl-auto: update
  datasource:
    url: ${USER_SVC_MYSQL_URL} 
    username: ${USER_SVC_MYSQL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${USER_SVC_MYSQL_PASSWORD}